# set the build version to simply be the incremental build number
version: '{build}'
image:
  - Visual Studio 2017
clone_folder: C:\projects\cpp-xplatform
branches:
  only:
    - master
# run a custom build through a script rather than MSBuild directly
build_script:
  - cd C:\projects\cpp-xplatform
  - cmake --version
  # note: I feed 'nul' into the batch file to cause it to exit once it hits the pause at its end, this is a fix to prevent appveyor from hanging for an hour, since no key could be pressed to terminate
  # https://stackoverflow.com/questions/11729562/disable-pause-in-windows-bat-script
  - dev-build-all.bat < nul
  # print out most of the generated files (note: hidden folders such as .vs/ will not be printed)
  - cd x86
  # tree graphically/recursively displays the folder structure. /F is used to display the names of the files in each folder. /A causes it to use ASCII characters (instead of extended characters that appveyor can't render)
  - tree /F /A
  - echo ======================================================
  - echo ======================================================
  # type <filename> prints out the file contents (similar to UNIX cat)
  - type cpp-xplatform.vcxproj
  - type CMakeCache.txt
  - echo ======================================================
  - echo ======================================================
  - cd ../x64
  - tree /F /A
  - echo ======================================================
  - echo ======================================================
  - type cpp-xplatform.vcxproj
  - type CMakeCache.txt