# set the build version to simply be the incremental build number
version: '{build}'
image:
  - Visual Studio 2017
clone_folder: C:\projects\cpp-xplatform
branches:
  only:
    - master
# run a custom build through a script rather than MSBuild directly
build_script:
  - cd C:\projects\cpp-xplatform
  - cmake --version
# note: I feed 'nul' into the batch file to cause it to exit once it hits the pause at its end, this is a fix to prevent appveyor from hanging for an hour, since no key could be pressed to terminate
# https://stackoverflow.com/questions/11729562/disable-pause-in-windows-bat-script
  - dev-build-all.bat < nul