language: cpp

# https://docs.travis-ci.com/user/reference/osx/
# each build in the matrix gets run on a fresh image of a VM
matrix:
  include:
    # https://docs.travis-ci.com/user/reference/bionic/
    # note: bionic (Ubuntu 18.04 LTS) comes with gcc 7.4.0 + clang/llvm 7
    - os: linux
      dist: bionic
      compiler: gcc
    - os: linux
      dist: bionic
      compiler: clang
    # https://docs.travis-ci.com/user/reference/osx/
    # macOS 10.13 and Xcode 9.4.1 by default, but i'm going to overwrite with a newer osx_image (macOS 10.13 and Xcode 10.0)
    # run clang front-end over LLVM back-end
    - os: osx
      osx_image: xcode10
      compiler: clang
    # run gcc front-end over LLVM back-end (not GNU-gcc)
    - os: osx
      osx_image: xcode10
      compiler: gcc
# https://stackoverflow.com/questions/34377017/what-are-the-differences-between-the-before-install-script-travis-yml-opti
install:
  # https://docs.travis-ci.com/user/reference/overview/
  # note: access to sudo command should be enabled by default (no need to place sudo: required at the top, I think...)
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt install tree; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install tree; fi
script:
  - cmake --version
  # print out file permissions to make sure shell script is executable (x-flag)
  - ls -l
  # note: I feed LICENSE file into the shell script to cause it to exit once it hits the pause at its end (reads first char in file), this is a fix to prevent travis from hanging for 10? minutes, since no key could be pressed to terminate
  - ./dev-build-all.sh < LICENSE
  # note: any directory changing within a shell script is isolated since it runs in a subshell
  # https://stackoverflow.com/questions/255414/why-doesnt-cd-work-in-a-shell-script
  # print out generated files
  - cd build
  # tree graphically/recursively displays the folder structure. -a is used to print all files (including hidden files)
  # https://www.geeksforgeeks.org/tree-command-unixlinux/
  - tree -a
  - echo ======================================================
  - echo ======================================================
  # DEBUG config...
  # print out file info for the executable (I want to see if x86 or x64)
  - file Debug/cpp-xplatform
  # print out these 2 files (useful info)
  - cat Debug/Makefile
  - cat Debug/CMakeCache.txt
  - echo ======================================================
  - echo ======================================================
  # MINSIZEREL config...
  # print out file info for the executable (I want to see if x86 or x64)
  - file MinSizeRel/cpp-xplatform
  # print out these 2 files (useful info)
  - cat MinSizeRel/Makefile
  - cat MinSizeRel/CMakeCache.txt
  - echo ======================================================
  - echo ======================================================
  # RELEASE config...
  # print out file info for the executable (I want to see if x86 or x64)
  - file Release/cpp-xplatform
  # print out these 2 files (useful info)
  - cat Release/Makefile
  - cat Release/CMakeCache.txt
  - echo ======================================================
  - echo ======================================================
  # RELWITHDEBINFO config...
  # print out file info for the executable (I want to see if x86 or x64)
  - file RelWithDebInfo/cpp-xplatform
  # print out these 2 files (useful info)
  - cat RelWithDebInfo/Makefile
  - cat RelWithDebInfo/CMakeCache.txt