language: cpp
matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
    - os: linux
      dist: bionic
      compiler: clang
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make