language: cpp

# https://docs.travis-ci.com/user/reference/osx/
# each build in the matrix gets run on a fresh image of a VM
matrix:
  include:
    # https://docs.travis-ci.com/user/reference/bionic/
    # note: bionic (Ubuntu 18.04 LTS) comes with gcc 7.4.0 + clang/llvm 7
    - os: linux
      dist: bionic
      compiler: gcc
    - os: linux
      dist: bionic
      compiler: clang
    # https://docs.travis-ci.com/user/reference/osx/
    # macOS 10.13 and Xcode 9.4.1 by default, but i'm going to overwrite with a newer osx_image (macOS 10.13 and Xcode 10.0)
    # run clang front-end over LLVM back-end
    - os: osx
      osx_image: xcode10
      compiler: clang
    # run gcc front-end over LLVM back-end (not GNU-gcc)
    - os: osx
      osx_image: xcode10
      compiler: gcc
# reference: https://docs.travis-ci.com/user/common-build-problems/#git-submodules-are-not-updated-correctly
# reference: https://github.com/algolia/examples/issues/24
# disable travis auto init/update of submodules (since it auto-detects a .gitmodules file)
git:
  submodules: false
before_install:
  - cd "${TRAVIS_BUILD_DIR}"
  - git submodule update --init --recursive
script:
  # reference: https://github.com/travis-ci/travis-ci/issues/1066
  # reference: https://travis-ci.community/t/multiline-script-not-failing-where-it-should/7644
  # enable fast-fail (exit script when a simple command fails)
  # note: the set -e/+e solution is unreliable (in particular, osx builds wrongly fail due to internal travis failures)
  # reference: https://github.com/travis-ci/docs-travis-ci-com/issues/1672
  # reference: https://travis-ci.community/t/build-fails-with-no-obvious-reason/1452
  # note: the '&& \' solution is improper syntax and YAML scalars (| or >) for multiline commands are annoying since they can't contain comments
  # reference: https://medium.com/@manjula.cse/how-to-stop-the-execution-of-travis-pipeline-if-script-exits-with-an-error-f0e5a43206bf
  # 'travis_terminate 1' hopefully is the best solution to fast-fail at the moment (but it seems like it may prevent after_script/after_failure blocks from running)
  # note: the best solution would probably be to move this script into a shell script and just execute that
  - cd "${TRAVIS_BUILD_DIR}" || travis_terminate 1
  - cmake --version || travis_terminate 1
  - cd scripts || travis_terminate 1
  # print out file permissions to make sure shell scripts are executable (x-flag)
  - ls -l || travis_terminate 1
  # note: I run the shell script with --no-pause option to cause it to exit without pausing at the end, this is a fix to prevent travis from hanging for 10? minutes, since no key could be pressed to terminate
  - ./dev-build-all.sh --no-pause || travis_terminate 1
  # note: any directory changing within a shell script is isolated since it runs in a subshell
  # https://stackoverflow.com/questions/255414/why-doesnt-cd-work-in-a-shell-script
  # print out generated files
  - cd ../build || travis_terminate 1
  # recursively search the directory structure from the current working directory (.) and print to console
  # http://man7.org/linux/man-pages/man1/find.1.html
  # the output of find is piped into sed (regex substitution) in order to make it look like an alias of tree command
  # http://osxdaily.com/2016/09/09/view-folder-tree-terminal-mac-os-tree-equivalent/
  # https://linux.die.net/man/1/sed
  # http://www.grymoire.com/Unix/Sed.html#uh-1
  # https://www.rexegg.com/regex-quickstart.html
  - find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g' || travis_terminate 1
  - echo ====================================================== || travis_terminate 1
  - echo ====================================================== || travis_terminate 1
  # DEBUG config...
  # print out file info for the executable (I want to see if x86 or x64)
  - file Debug/project-name || travis_terminate 1
  # print out these 3 files (useful info)
  - cat Debug/compile_commands.json || travis_terminate 1
  - cat Debug/Makefile || travis_terminate 1
  - cat Debug/CMakeCache.txt || travis_terminate 1
  - echo ====================================================== || travis_terminate 1
  - echo ====================================================== || travis_terminate 1
  # MINSIZEREL config...
  # print out file info for the executable (I want to see if x86 or x64)
  - file MinSizeRel/project-name || travis_terminate 1
  # print out these 3 files (useful info)
  - cat MinSizeRel/compile_commands.json || travis_terminate 1
  - cat MinSizeRel/Makefile || travis_terminate 1
  - cat MinSizeRel/CMakeCache.txt || travis_terminate 1
  - echo ====================================================== || travis_terminate 1
  - echo ====================================================== || travis_terminate 1
  # RELEASE config...
  # print out file info for the executable (I want to see if x86 or x64)
  - file Release/project-name || travis_terminate 1
  # print out these 3 files (useful info)
  - cat Release/compile_commands.json || travis_terminate 1
  - cat Release/Makefile || travis_terminate 1
  - cat Release/CMakeCache.txt || travis_terminate 1
  - echo ====================================================== || travis_terminate 1
  - echo ====================================================== || travis_terminate 1
  # RELWITHDEBINFO config...
  # print out file info for the executable (I want to see if x86 or x64)
  - file RelWithDebInfo/project-name || travis_terminate 1
  # print out these 3 files (useful info)
  - cat RelWithDebInfo/compile_commands.json || travis_terminate 1
  - cat RelWithDebInfo/Makefile || travis_terminate 1
  - cat RelWithDebInfo/CMakeCache.txt || travis_terminate 1
  - echo ====================================================== || travis_terminate 1
  - echo ====================================================== || travis_terminate 1
  - cd ../scripts || travis_terminate 1
  - ./run-internal-tests.sh --no-pause || travis_terminate 1
  - ./run-external-tests.sh --no-pause || travis_terminate 1
